/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TELAS;

import DAO.CadastroDAO;
import DTO.CadastroDTO;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import TELAS.CadastroCliente;

/**
 *
 * @author Nadya
 */
public class ConsultarCliente extends javax.swing.JFrame {

    /**
     * Creates new form ConsultarCadastro
     */
    public ConsultarCliente() {
        initComponents();
        listarValores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaCliente = new javax.swing.JTable();
        VOLTAR = new javax.swing.JButton();
        Pesquisar = new javax.swing.JButton();
        ATUALIZARDADOS = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        campoid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        campocpf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        camponome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        camposobrenome = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        campodn = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        campotipotelefone = new javax.swing.JTextField();
        campotelefone = new javax.swing.JTextField();
        campocep = new javax.swing.JTextField();
        campotipologradouro = new javax.swing.JTextField();
        campologradouro = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        camponumero = new javax.swing.JTextField();
        campobairro = new javax.swing.JTextField();
        campocidade = new javax.swing.JTextField();
        campoestado = new javax.swing.JTextField();
        CARREGARDADOS = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TabelaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "", "CPF", "Nome", "Sobrenome", "Data de Nascimento", "Tipo Telefone", "Telefone", "CEP", "Tipo Logradouro", "Logradouro", "Numero", "Bairro", "Cidade", "UF"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TabelaCliente);
        if (TabelaCliente.getColumnModel().getColumnCount() > 0) {
            TabelaCliente.getColumnModel().getColumn(0).setPreferredWidth(2);
            TabelaCliente.getColumnModel().getColumn(1).setPreferredWidth(60);
            TabelaCliente.getColumnModel().getColumn(2).setPreferredWidth(50);
            TabelaCliente.getColumnModel().getColumn(3).setPreferredWidth(100);
            TabelaCliente.getColumnModel().getColumn(4).setPreferredWidth(40);
            TabelaCliente.getColumnModel().getColumn(5).setPreferredWidth(30);
            TabelaCliente.getColumnModel().getColumn(6).setPreferredWidth(30);
            TabelaCliente.getColumnModel().getColumn(7).setPreferredWidth(20);
            TabelaCliente.getColumnModel().getColumn(8).setPreferredWidth(10);
            TabelaCliente.getColumnModel().getColumn(9).setPreferredWidth(80);
            TabelaCliente.getColumnModel().getColumn(10).setPreferredWidth(5);
            TabelaCliente.getColumnModel().getColumn(11).setPreferredWidth(70);
            TabelaCliente.getColumnModel().getColumn(12).setPreferredWidth(70);
            TabelaCliente.getColumnModel().getColumn(13).setPreferredWidth(5);
        }

        VOLTAR.setText("VOLTAR");
        VOLTAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VOLTARActionPerformed(evt);
            }
        });

        Pesquisar.setText("EXCLUIR");
        Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesquisarActionPerformed(evt);
            }
        });

        ATUALIZARDADOS.setText("ATUALIZAR DADOS");
        ATUALIZARDADOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ATUALIZARDADOSActionPerformed(evt);
            }
        });

        jLabel1.setText("Id Cliente");

        campoid.setText("                ");

        jLabel2.setText("CPF:");

        campocpf.setText("               ");

        jLabel3.setText("NOME:");

        camponome.setText("                ");

        jLabel4.setText("SOBRENOME:");

        camposobrenome.setText("            ");

        jLabel5.setText("DATA DE NASCIMENTO:");

        campodn.setText("           ");

        jLabel6.setText("TIPO TELEFONE:");

        jLabel7.setText("TELEFONE:");

        jLabel8.setText("CEP:");

        jLabel9.setText("TIPO LOGRADOURO:");

        jLabel10.setText("LOGRADOURO:");

        campotipotelefone.setText("          ");

        campotelefone.setText("           ");

        campocep.setText("        ");

        campotipologradouro.setText("      ");

        jLabel11.setText("NUMERO:");

        jLabel12.setText("BAIRRO:");

        jLabel13.setText("CIDADE:");

        jLabel14.setText("ESTADO:");

        camponumero.setText("       ");

        campobairro.setText("     ");

        campocidade.setText(" ");

        CARREGARDADOS.setText("CARREGAR DADOS");
        CARREGARDADOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CARREGARDADOSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Pesquisar)
                .addGap(27, 27, 27)
                .addComponent(VOLTAR)
                .addGap(247, 247, 247))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1279, Short.MAX_VALUE)
                        .addGap(114, 114, 114))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(camposobrenome))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campodn, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(campoid, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                                    .addComponent(campocpf)
                                    .addComponent(camponome))))
                        .addGap(96, 96, 96)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(campotipotelefone)
                                    .addComponent(campotelefone, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campologradouro))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campotipologradouro))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                                .addComponent(campocep, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(18, 18, 18)
                                        .addComponent(camponumero, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(18, 18, 18)
                                        .addComponent(campobairro))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(18, 18, 18)
                                        .addComponent(campocidade))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(campoestado))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(175, 175, 175)
                                .addComponent(CARREGARDADOS)
                                .addGap(29, 29, 29)
                                .addComponent(ATUALIZARDADOS)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(campoid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(campotipotelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(camponumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campocpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(campotelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(campobairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(camponome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(campocep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(campocidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(camposobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(campotipologradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(campoestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(campodn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(campologradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CARREGARDADOS)
                    .addComponent(ATUALIZARDADOS))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pesquisar)
                    .addComponent(VOLTAR))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Clientes", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ATUALIZARDADOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ATUALIZARDADOSActionPerformed
        Atualizacliente();
        listarValores();
        LimparCampos();

    }//GEN-LAST:event_ATUALIZARDADOSActionPerformed

    private void PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesquisarActionPerformed
        CarregarDados();
        Excluircliente();
        listarValores();
        LimparCampos();
    }//GEN-LAST:event_PesquisarActionPerformed

    private void VOLTARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VOLTARActionPerformed
        TelaPrincipal objTelaPrincipal = new TelaPrincipal();
        objTelaPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VOLTARActionPerformed

    private void CARREGARDADOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CARREGARDADOSActionPerformed
        CarregarDados();
    }//GEN-LAST:event_CARREGARDADOSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ATUALIZARDADOS;
    private javax.swing.JToggleButton CARREGARDADOS;
    private javax.swing.JButton Pesquisar;
    private javax.swing.JTable TabelaCliente;
    private javax.swing.JButton VOLTAR;
    private javax.swing.JTextField campobairro;
    private javax.swing.JTextField campocep;
    private javax.swing.JTextField campocidade;
    private javax.swing.JTextField campocpf;
    private javax.swing.JTextField campodn;
    private javax.swing.JTextField campoestado;
    private javax.swing.JTextField campoid;
    private javax.swing.JTextField campologradouro;
    private javax.swing.JTextField camponome;
    private javax.swing.JTextField camponumero;
    private javax.swing.JTextField camposobrenome;
    private javax.swing.JTextField campotelefone;
    private javax.swing.JTextField campotipologradouro;
    private javax.swing.JTextField campotipotelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

    private void listarValores() {

        CadastroDAO objcadastrodao = new CadastroDAO();
        DefaultTableModel model = (DefaultTableModel) TabelaCliente.getModel();
        model.setNumRows(0);
        ArrayList<CadastroDTO> lista = objcadastrodao.ConsultarCliente();
        for (int num = 0; num < lista.size(); num++) {
            model.addRow(new Object[]{
                lista.get(num).getIdCliente(),
                lista.get(num).getCPF(),
                lista.get(num).getNome(),
                lista.get(num).getSobrenome(),
                lista.get(num).getDatadeNascimento(),
                lista.get(num).getTipoTelefone(),
                lista.get(num).getTelefone(),
                lista.get(num).getCep(),
                lista.get(num).getTipoLogradouro(),
                lista.get(num).getLogradouro(),
                lista.get(num).getNumero(),
                lista.get(num).getBairro(),
                lista.get(num).getCidade(),
                lista.get(num).getEstado()

            });
        }
    }

    private void CarregarDados() {
        int setar = TabelaCliente.getSelectedRow();

        campoid.setText(TabelaCliente.getModel().getValueAt(setar, 0).toString());
        campocpf.setText(TabelaCliente.getModel().getValueAt(setar, 1).toString());
        camponome.setText(TabelaCliente.getModel().getValueAt(setar, 2).toString());
        camposobrenome.setText(TabelaCliente.getModel().getValueAt(setar, 3).toString());
        campodn.setText(TabelaCliente.getModel().getValueAt(setar, 4).toString());
        campotipotelefone.setText(TabelaCliente.getModel().getValueAt(setar, 5).toString());
        campotelefone.setText(TabelaCliente.getModel().getValueAt(setar, 6).toString());
        campocep.setText(TabelaCliente.getModel().getValueAt(setar, 7).toString());
        campotipologradouro.setText(TabelaCliente.getModel().getValueAt(setar, 8).toString());
        campologradouro.setText(TabelaCliente.getModel().getValueAt(setar, 9).toString());
        camponumero.setText(TabelaCliente.getModel().getValueAt(setar, 10).toString());
        campobairro.setText(TabelaCliente.getModel().getValueAt(setar, 11).toString());
        campocidade.setText(TabelaCliente.getModel().getValueAt(setar, 12).toString());
        campoestado.setText(TabelaCliente.getModel().getValueAt(setar, 13).toString());

    }

    private void LimparCampos() {
        campoid.setText("");
        campocpf.setText("");
        camponome.setText("");
        camposobrenome.setText("");
        campodn.setText("");
        campotipotelefone.setText("");
        campotelefone.setText("");
        campocep.setText("");
        campotipologradouro.setText("");
        campologradouro.setText("");
        camponumero.setText("");
        campobairro.setText("");
        campocidade.setText("");
        campoestado.setText("");
        campocpf.requestFocus();

    }

    private void Cadastrar() {
        String CPF, Nome, Sobrenome, DatadeNascimento, CEP, TipoLogradouro, Logradouro, Numero, Bairro, Cidade, Estado, TipoTelefone, Telefone;

        CPF = campocpf.getText();
        Nome = camponome.getText();
        Sobrenome = camposobrenome.getText();
        DatadeNascimento = campodn.getText();
        System.out.println(DatadeNascimento);
        CEP = campocep.getText();
        TipoLogradouro = campotipologradouro.getText();
        Logradouro = campologradouro.getText();
        Numero = camponumero.getText();
        Bairro = campobairro.getText();
        Cidade = campocidade.getText();
        Estado = campoestado.getText();
        TipoTelefone = campotipotelefone.getText();
        Telefone = campotelefone.getText();

        CadastroDTO objcadastrodto = new CadastroDTO();
        objcadastrodto.setCPF(CPF);
        objcadastrodto.setNome(Nome);
        objcadastrodto.setSobrenome(Sobrenome);
        objcadastrodto.setDatadeNascimento(DatadeNascimento);
        objcadastrodto.setCep(CEP);
        objcadastrodto.setTipoLogradouro(TipoLogradouro);
        objcadastrodto.setLogradouro(Logradouro);
        objcadastrodto.setNumero(Numero);
        objcadastrodto.setBairro(Bairro);
        objcadastrodto.setCidade(Cidade);
        objcadastrodto.setEstado(Estado);
        objcadastrodto.setTipoTelefone(TipoTelefone);
        objcadastrodto.setTelefone(Telefone);

        CadastroDAO objclientedao = new CadastroDAO();
        objclientedao.cadastrocliente(objcadastrodto);
    }

    private void Atualizacliente() {
        int IdCliente;
        String CPF, Nome, Sobrenome, DatadeNascimento, TipoTelefone, Telefone, CEP, TipoLogradouro, Logradouro, Numero, Bairro, Cidade, Estado;

        IdCliente = Integer.parseInt(campoid.getText());
        CPF = campocpf.getText();
        Nome = camponome.getText();
        Sobrenome = camposobrenome.getText();
        DatadeNascimento = campodn.getText();
        CEP = campocep.getText();
        TipoLogradouro = campotipologradouro.getText();
        Logradouro = campologradouro.getText();
        Numero = camponumero.getText();
        Bairro = campobairro.getText();
        Cidade = campocidade.getText();
        Estado = campoestado.getText();
        TipoTelefone = campotipotelefone.getText();
        Telefone = campotelefone.getText();

        CadastroDTO objclientedto = new CadastroDTO();
        objclientedto.setIdCliente(IdCliente);
        objclientedto.setCPF(CPF);
        objclientedto.setNome(Nome);
        objclientedto.setSobrenome(Sobrenome);
        objclientedto.setDatadeNascimento(DatadeNascimento);
        objclientedto.setTipoTelefone(TipoTelefone);
        objclientedto.setTelefone(Telefone);
        objclientedto.setTipoLogradouro(TipoLogradouro);
        objclientedto.setLogradouro(Logradouro);
        objclientedto.setCep(CEP);
        objclientedto.setNumero(Numero);
        objclientedto.setBairro(Bairro);
        objclientedto.setCidade(Cidade);
        objclientedto.setEstado(Estado);

        CadastroDAO objclientedao = new CadastroDAO();
        objclientedao.Atualizarcliente(objclientedto);

    }

    private void Excluircliente() {
        int IdCliente;

        IdCliente = Integer.parseInt(campoid.getText());

        CadastroDTO objclientedto = new CadastroDTO();
        objclientedto.setIdCliente(IdCliente);

        CadastroDAO objclientedao = new CadastroDAO();
        objclientedao.Excluircliente(objclientedto);

    }

}
